import css from './css.svg'
import electron from './electron.svg'
import flutter from './flutter.svg'
import git from './git.svg'
import gitlab from './gitlab.svg'
import html from './html.svg'
import javascript from './javascript.svg'
import postcss from './postcss.svg'
import sass from './sass.svg'
import slack from './slack.svg'
import typescript from './typescript.svg'
import vite from './vite.svg'
import vuejs from './vuejs.svg'
import webpack from './webpack.svg'

export { vuejs, javascript, typescript, flutter, sass, html, css, webpack, vite, electron, git, gitlab, slack, postcss }
